name: shopping
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=2.18.5 <3.0.0'

dependencies:
  carousel_slider: ^4.2.1
  cupertino_icons: ^1.0.2
  dots_indicator: ^2.1.0
  flutter:
    sdk: flutter
  get: 4.6.5

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  lints: 2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
